---
# Pour exÃ©cuter via ansible
#     ansible-playbook -i hosts 10-playbook-conditions.yml

# ðŸ” Doc : https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_conditionals.html

- name: Syntaxe utiliser des conditions
  hosts: 127.0.0.1
  connection: local
  vars:
    # Mots clÃ©s rÃ©servÃ©s true false, Ã©glament d'autres maniÃ¨res de les Ã©crire
    #   Ils peuvent Ãªtre calculÃ©s, ou le rÃ©sultat de vÃ©rifications (ex: est-ce qu'un fichier existe ?)
    ma_variable_booleene_vraie: true
    ma_variable_booleene_false: false

  tasks:
    - debug:
        msg: "La premiÃ¨re variable est vraie"
      when: ma_variable_booleene_vraie
    
    # Cette tÃ¢che ne sera pas exÃ©cutÃ©e : skipping (la tÃ¢che est passÃ©e / omise)
    - debug:
        msg: "La premiÃ¨re variable est fausse"
      when: not ma_variable_booleene_vraie
    
    - debug:
        msg: "La deuxiÃ¨me variable est fausse"
      when: not ma_variable_booleene_false

    
    - debug:
        msg: "L'une des deux variable est vraie"
      # OU logique : soit l'une soit l'autre
      when: ma_variable_booleene_vraie or ma_variable_booleene_false | bool

    # PossibilitÃ© d'utiliser le ET logique "and", les opÃ©rateurs mathÃ©matiques >, <, etc.
...
